[package]
name = "templatevalidator"
version = "0.1.0"
authors = ["gamak"]
edition = "2018"

[lib]
name = "templatevalidator"
path = "lib.rs"

[dependencies]
failure = "0.1.3"
colored = "1.6.1"
serde_json = "1.0.33"
os_type = "2.2.0"